# Generated by Django 5.2.7 on 2026-02-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="sort_order",
            field=models.IntegerField(default=0),
        ),
    ]
